name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.0

      ##Builds
      - name: Install dependencies Api
        run: dotnet restore Api/Api
      - name: Build
        run:  dotnet build --configuration Release --no-restore Api/Api

      ##Tests
      - name: Test Api List
        run: dotnet test UnitTests/UnitTests -t
      - name: Test Api
        run: dotnet test UnitTests/UnitTests  --no-restore --verbosity n  -l "console;verbosity=detailed"